---
- hosts: redhat
  become: yes
  remote_user: ansible


  tasks:   
  - name: Open firewall ports
    firewalld: 
      port: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - 8080/tcp 
       
