---
- hosts: redhat
  become: yes
  remote_user: ansible

  tasks:

  - name: Install apache
    yum:
      name: httpd
      state: present

  - name: Start and enabled httpd service
    service:
      name: httpd
      enabled: true
      state: started


  - name: Open firewall ports
    firewalld: 
      service: "{{ item }}"
      state: enabled
      permanent: true
      immediate: true
    loop:
    - http
    - https    
  
  - name: Copy virtualhost
    ansible.builtin.copy:
      src: ./virtualhost.conf
      dest: /etc/httpd/conf.d/
      owner: apache
      group: apache
      mode: '0644'
  
  - name: Allow SELinux
    ansible.posix.seboolean:
      name: httpd_can_network_connect
      state: true
      persistent: true
  
  - name: Restart apache
    systemd:
      name: httpd
      state: restarted

# Install apache on Ubuntu

- hosts: ubuntu
  become: yes
  remote_user: ansible

  tasks:

  - name: Install Apache Ubuntu
    apt:
      name: apache2
      update_cache: yes
      state: latest

  - name: Start and enabled httpd service
    service:
      name: apache2
      enabled: yes
      state: started

  - name: Open firewall ports
    ufw:
      rule: allow
      port: "{{ item }}"
      state: enabled
      proto: tcp

    loop:
     - 80 # http
     - 443 # https
    notify: Reload UFW

  handlers:
  - name: Reload UFW
    ufw:
      state: reloaded

