---
- hosts: redhat
  become: yes
  remote_user: ansible

  tasks: 
  
  - name: Install EPEL
    yum:
     name: epel-release

  - name: Install Podman
    yum:
     name: podman


  - name: Enable Podman service
    systemd:
        name: podman
        state: started
        enabled: yes
  
  - name: Run Podman
    command: >
      podman run -d -p 8081:8080 -v /var/lib/tomcat/webapps/todo:/usr/local/tomcat/webapps/todo:Z -v /opt/config/:/opt/config/:Z tomcat:9   
